services:
  taxo:
    volumes:
      - ./:/root/TaxoComplete
    image: "taxocomplete:latest"
    command: bash -c "tail -f /dev/null"
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]